### ISSUE TITLE
Consistent zoom level in external map services

### ISSUE THREAD

**Issue by axelpale** [axelpale/georap#156]
"More maps" feature allows viewing the current location on various geographic map services. Currently, the center of the view match but the zoom level does not. The google maps zoom level cannot be used directly because the scales for z differ from service to service. Find a function for each external service that maps the google maps zoom level to a zoom level in external service that produces about similar view.

**Comment by mikatammi** [comment]
GeoHack uses these strange "types" (country, state, landmark, etc.) for generating the zoom levels to all services it generates links to, described here:
https://www.mediawiki.org/wiki/GeoHack#params

**Comment by axelpale** [comment]
For GeoHack, what if:

    type = (zoom < 10) ? 'landmark' : 'city'

**Comment by mikatammi** [comment]
(zoom <= 5) ? "country" : (zoom <= 8) ? "state" : (zoom <= 10) ? "adm1st" : (zoom <= 11) ? "adm2nd" : (zoom <= 12) ? "adm3rd" : (zoom <= 13) ? "event" : (zoom <= 14) ? "airport" : "landmark"

**Comment by mikatammi** [comment]
Lantmäteriet zoom levels 0 .. 15

Lantmäteriet - Georap (Google)
0 - 4
12 - 16
16 - 19..20

**Comment by mikatammi** [comment]
Finn.no zoom levels 4 .. 21

Finn.no - Georap (Google)
4 - 4
21 - 21

Matches with Google

**Comment by mikatammi** [comment]
Gule Sider levels 3 .. 20
3 - 3
20 - 20

Matches with Google

**Comment by axelpale** [comment]
Much usability, wow zooms!
