### ISSUE TITLE
Browser does not start GPS

### ISSUE THREAD

**Issue by axelpale** [axelpale/georap#93]
A native application starts the GPS automatically. We found out that location in TresDB works only after a native application that uses GPS, like Google Maps, is first launched.

**Comment by axelpale** [comment]
See this Google dev post https://developers.google.com/web/fundamentals/native-hardware/user-location/

**Comment by mikatammi** [comment]
It might be this, it is possible to define optional third parameter for navigator.geolocation.watchPosition which specifies geoOptions.
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/watchPosition
https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPosition

**Comment by axelpale** [comment]
Yes! Now the progressive web app and the browser start up the GPS when needed. Great success.
